
os: linux
arch: ppc64le
language: shell
services: 
  - docker
script:
  - uname -p
  - echo $TRAVIS_DIST
  - docker run --privileged ubuntu:23.04 echo "Hello, world!"
  - docker run quay.io/podman/stable echo "Hello, world!"
  - docker pull ubuntu:23.04
  - docker images
  - docker run --privileged quay.io/podman/stable echo "Hello, world!"

jobs: 
  include:
    - dist: xenial
    - dist: binoic
    - dist: focal
    - dist: jammy
